
included: # 设置源文件目录
  - Sources
  - Example

disabled_rules:
  - trailing_whitespace
  - trailing_comma
file_length:
  ignore_comment_only_lines: true # 不应该限制文件内的注释大小
line_length:
  warning: 180
  ignores_urls: true # URL应该保持完整，不换行
  ignores_interpolated_strings: true
identifier_name:
  min_length: 2
  excluded:
    - i
    - j
    - k
    - v