name: Example
options:
  bundleIdPrefix: com.github.yaochenfeng
packages:
  RXKit:
    path: ../RXKit
targets:
  Example:
    platform: iOS
    type: application
    deploymentTarget: "11.0"
    sources:
      - Example
    postCompileScripts:
      - name: Swiftlint
        basedOnDependencyAnalysis: false
        script: |
                if which swiftlint > /dev/null; then
                  swiftlint
                else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        
        
    dependencies:
      - package:   RXKit
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen.storyboard
        MARKETING_VERSION: 1.0.0
        GENERATE_INFOPLIST_FILE: true
