name: Example
options:
  bundleIdPrefix: com.github.yaochenfeng
  deploymentTarget:
    iOS: "12.0"
  postGenCommand: bundle exec pod install

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1

targets:
  Example:
    type: application
    platform: iOS
    sources: [Example]
    preBuildScripts:
      - name: lintAndGen
        basedOnDependencyAnalysis: false
        script: "${PODS_ROOT}/SwiftGen/bin/swiftgen && ${PODS_ROOT}/SwiftLint/swiftlint"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        ENABLE_PREVIEWS: YES
