on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please
jobs:
  release-please:
    runs-on: macOS-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          # Use https://github.com/googleapis/release-please/blob/main/src/strategies/ruby.ts Release Type.
          release-type: simple
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

      - name: Release Gem
        run: |
          gem install bundler
          bundle install
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
